development:
  adapter: oracle_enhanced
  host: 192.168.1.4
  port: 1521
  database: orcl
  username: dragos
  password: dragos

test:
  adapter: oracle_enhanced
  database: orcl
  username: dragos
  password: dragos

production:
  adapter: oracle_enhanced
  database: orcl
  username: dragos
  password: dragos
